title: Jeongwon blog
email: onethegarden@gmail.com
description: 
baseurl: "/Mekyll" # the subpath of your site, e.g. /blog
url: "https://onethegarden.github.io" 
postCount: 5 # the number of posts on the "index" page

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink   : /:year/:title/
source: ./
destination: ./_site

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
